obj-$(CONFIG_MXC_IPU_V1)			+= ipu/
obj-$(CONFIG_MXC_IPU_V3)			+= ipu3/
obj-$(CONFIG_MXC_SSI)               	+= ssi/
obj-$(CONFIG_MXC_DAM)               	+= dam/

obj-$(CONFIG_MXC_PMIC)			+= pmic/

obj-$(CONFIG_MXC_DPTC)			+= pm/
obj-$(CONFIG_MX27_DPTC)			+= pm/
obj-$(CONFIG_MXC_HMP4E)         	+= hmp4e/
obj-y                                   += security/
obj-$(CONFIG_MXC_VPU)                   += vpu/
obj-$(CONFIG_MXC_HWEVENT)               += hw_event/
