# Makefile for the Linux MXC Security API
obj-$(CONFIG_MXC_SECURITY_SCC) += mxc_scc.o
obj-$(CONFIG_MXC_SECURITY_RTIC) += mxc_rtic.o
obj-$(CONFIG_MXC_SECURITY_HAC) += mxc_hacc.o
obj-$(CONFIG_MXC_SECURITY_RNG) += rng/
obj-$(CONFIG_MXC_SECURITY_CORE) += mxc_sec_mod.o
obj-$(CONFIG_MXC_SAHARA) += sahara2/
